In [29]:
# Bài 1 nominal data
import pandas as pd

df = pd.read_csv("data/car.data")
df

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [30]:
from sklearn.preprocessing import LabelBinarizer

# Xu li nominal datax
data = pd.DataFrame()
columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "classify"]
for index, col in enumerate(columns):
    if col != "classify":
        data = pd.concat([data, pd.get_dummies(df.iloc[:,index], prefix=col)], axis=1)

print(data)

X = data.values
print(X)

      buying_high  buying_low  buying_med  buying_vhigh  maint_high  \
0               0           0           0             1           0
1               0           0           0             1           0
2               0           0           0             1           0
3               0           0           0             1           0
4               0           0           0             1           0
...           ...         ...         ...           ...         ...
1722            0           1           0             0           0
1723            0           1           0             0           0
1724            0           1           0             0           0
1725            0           1           0             0           0
1726            0           1           0             0           0

      maint_low  maint_med  maint_vhigh  doors_2  doors_3  ...  doors_5more  \
0             0          0            1        1        0  ...            0
1             0          0            1        1        0  ...            0
2             0          0            1        1        0  ...            0
3             0          0            1        1        0  ...            0
4             0          0            1        1        0  ...            0
...         ...        ...          ...      ...      ...  ...          ...
1722          1          0            0        0        0  ...            1
1723          1          0            0        0        0  ...            1
1724          1          0            0        0        0  ...            1
1725          1          0            0        0        0  ...            1
1726          1          0            0        0        0  ...            1

      persons_2  persons_4  persons_more  lug_boot_big  lug_boot_med  \
0             1          0             0             0             0
1             1          0             0             0             0
2             1          0             0             0             1
3             1          0             0             0             1
4             1          0             0             0             1
...         ...        ...           ...           ...           ...
1722          0          0             1             0             1
1723          0          0             1             0             1
1724          0          0             1             1             0
1725          0          0             1             1             0
1726          0          0             1             1             0

      lug_boot_small  safety_high  safety_low  safety_med
0                  1            0           0           1
1                  1            1           0           0
2                  0            0           1           0
3                  0            0           0           1
4                  0            1           0           0
...              ...          ...         ...         ...
1722               0            0           0           1
1723               0            1           0           0
1724               0            0           1           0
1725               0            0           0           1
1726               0            1           0           0

[1727 rows x 21 columns]
[[0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 0 1]
 [0 1 0 ... 1 0 0]]

In [31]:
y_nominal = df.iloc[:,-1].values
y = pd.get_dummies(y_nominal, prefix="classify")
print(y)

y = y.values
print(y)

      classify_acc  classify_good  classify_unacc  classify_vgood
0                0              0               1               0
1                0              0               1               0
2                0              0               1               0
3                0              0               1               0
4                0              0               1               0
...            ...            ...             ...             ...
1722             0              1               0               0
1723             0              0               0               1
1724             0              0               1               0
1725             0              1               0               0
1726             0              0               0               1

[1727 rows x 4 columns]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 ...
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]

In [32]:
import sklearn.model_selection as model_selection

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.5, train_size=0.5, random_state=4)

In [33]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics

accuracy_list = []
for num_neighbor in range(1, 51):
    knn = KNeighborsClassifier(n_neighbors=num_neighbor, weights='distance', metric='euclidean')
    knn.fit(X_train,y_train)

    y_predict = knn.predict(X_test)

    #Tinh do chinh xac
    acc_score = metrics.accuracy_score(y_predict,y_test)
    accuracy_list.append(acc_score)

max_acc = accuracy_list[0]
max_index = 0
for index in range(0, len(accuracy_list)):
    if accuracy_list[index] > max_acc:
        max_acc = accuracy_list[index]
        max_index = index + 1

print("K toi uu nhat:", max_index)
print("Accuracy:", max_acc)

K toi uu nhat: 5
Accuracy: 0.8657407407407407

In [8]:
# Bài 2 dữ liệu numeric
df2 = pd.read_csv("data/winequality-red.csv")
df2

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [24]:
data = df2.values
X = data[:,:-1]
y = data[:,-1]
print(X)
print(y)

[[ 7.4    0.7    0.    ...  3.51   0.56   9.4  ]
 [ 7.8    0.88   0.    ...  3.2    0.68   9.8  ]
 [ 7.8    0.76   0.04  ...  3.26   0.65   9.8  ]
 ...
 [ 6.3    0.51   0.13  ...  3.42   0.75  11.   ]
 [ 5.9    0.645  0.12  ...  3.57   0.71  10.2  ]
 [ 6.     0.31   0.47  ...  3.39   0.66  11.   ]]
[5. 5. 5. ... 6. 5. 6.]

In [25]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
print(X)

[[0.24778761 0.39726027 0.         ... 0.60629921 0.13772455 0.15384615]
 [0.28318584 0.52054795 0.         ... 0.36220472 0.20958084 0.21538462]
 [0.28318584 0.43835616 0.04       ... 0.40944882 0.19161677 0.21538462]
 ...
 [0.15044248 0.26712329 0.13       ... 0.53543307 0.25149701 0.4       ]
 [0.11504425 0.35958904 0.12       ... 0.65354331 0.22754491 0.27692308]
 [0.12389381 0.13013699 0.47       ... 0.51181102 0.19760479 0.4       ]]

In [26]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.5, train_size=0.5, random_state=4)

accuracy_list2 = []
for num_neighbor in range(1, 101):
    knn = KNeighborsClassifier(n_neighbors=num_neighbor, weights='distance', metric='euclidean')
    knn.fit(X_train,y_train)

    y_predict = knn.predict(X_test)

    #Tinh do chinh xac
    acc_score = metrics.accuracy_score(y_predict,y_test)
    accuracy_list2.append(acc_score)

max_acc2 = accuracy_list2[0]
max_index = 0
for index in range(0, len(accuracy_list2)):
    if accuracy_list2[index] > max_acc:
        max_acc = accuracy_list2[index]
        max_index = index + 1

print("K toi uu nhat:", max_index)
print("Accuracy:", max_acc2)

K toi uu nhat: 74
Accuracy: 0.585